services:
  rucio:
    image: docker.io/rucio/rucio-dev
    extra_hosts:
      - "ruciodb:127.0.0.1"
      - "graphite:127.0.0.1"
      - "fts:127.0.0.1"
      - "ftsdb:127.0.0.1"
      - "xrd1:127.0.0.1"
      - "activemq:127.0.0.1"
      - "ssh1:127.0.0.1"
    ports:
      - "127.0.0.1:8443:443"
      - "127.0.0.1:5432:5432"
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8446:8446"
      - "127.0.0.1:8449:8449"
      - "127.0.0.1:3306:3306"
      - "127.0.0.1:1094:1094"
      - "127.0.0.1:61613:61613"
      - "127.0.0.1:2222:22"
    volumes:
      - /home/wilko/gitrepos/github/klabattermann/psdme-rucio:/home
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS=postgres14
  ruciodb:
    image: docker.io/postgres:14
    network_mode: "service:rucio"
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
    volumes:
      - /home/wilko/var:/var/lib/postgresql/data
      - /tmp:/tmp
  fts:
    image: docker.io/rucio/fts
    network_mode: "service:rucio"
  ftsdb:
    image: docker.io/mysql:8
    network_mode: "service:rucio"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
  xrd1:
    image: docker.io/rucio/xrootd
    network_mode: "service:rucio"
    environment:
      - XRDPORT=1094
    volumes:
      - /home/wilko/data/xrd:/rucio
      - ../../certs/hostcert_xrd1.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem:Z
