version: "2"
services:
  rucio:
    image: rucio/rucio-dev
    ports:
      - "443:443"
    links:
      - mysql:mysql
      - graphite:graphite
    volumes:
      - ../../../tools:/opt/rucio/tools
      - ../../../bin:/opt/rucio/bin
      - ../../../lib:/opt/rucio/lib
      - /etc/grid-security:/etc/grid-security
      - /home/wilko/github/klabattermann/psdme-rucio:/opt/wk
      - /home/wilko/data:/reg/d/psdm
      - /home/wilko/cfg:/opt/cfg
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
